# Generated by Django 3.2 on 2022-01-17 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='role_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(blank=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('empid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='referral_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_ph', models.IntegerField(max_length=10)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('doc_name', models.CharField(max_length=30, null=True)),
                ('doc_ph', models.IntegerField(max_length=10)),
                ('ip_no', models.IntegerField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('admission_date', models.DateField()),
                ('confirm', models.BooleanField(blank=True, default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.IntegerField(blank=True, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=13)),
                ('dept', models.CharField(blank=True, max_length=50)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
