# Generated by Django 3.2 on 2022-01-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMHOnlinePatRfrApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral_details',
            name='patient_add',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
