# Generated by Django 3.2 on 2022-01-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMHOnlinePatRfrApp', '0002_referral_details_patient_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral_details',
            name='date',
        ),
        migrations.RemoveField(
            model_name='referral_details',
            name='time',
        ),
        migrations.AddField(
            model_name='referral_details',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='referral_details',
            name='doc_ph',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='referral_details',
            name='ip_no',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='referral_details',
            name='patient_ph',
            field=models.CharField(max_length=10),
        ),
    ]
