# Generated by Django 3.2 on 2022-01-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMHOnlinePatRfrApp', '0003_auto_20220117_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral_details',
            name='admission_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
