# Generated by Django 3.2 on 2022-01-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMHOnlinePatRfrApp', '0004_alter_referral_details_admission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral_details',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='referral_details',
            name='admission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Admission Date'),
        ),
        migrations.AlterField(
            model_name='referral_details',
            name='confirm',
            field=models.BooleanField(blank=True, default=0, verbose_name='Click to Confirm Admission'),
        ),
        migrations.AlterField(
            model_name='referral_details',
            name='doc_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Referred by'),
        ),
        migrations.AlterField(
            model_name='referral_details',
            name='doc_ph',
            field=models.CharField(max_length=10, verbose_name='Referred by Phone'),
        ),
        migrations.AlterField(
            model_name='referral_details',
            name='ip_no',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='referral_details',
            name='patient_add',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Patient Address'),
        ),
        migrations.AlterField(
            model_name='referral_details',
            name='patient_name',
            field=models.CharField(max_length=50, verbose_name='Patient Name'),
        ),
        migrations.AlterField(
            model_name='referral_details',
            name='patient_ph',
            field=models.CharField(max_length=10, verbose_name='Patient Phone'),
        ),
    ]
