# Generated by Django 3.2 on 2022-02-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMHOnlinePatRfrApp', '0005_auto_20220118_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral_details',
            name='patient_type',
            field=models.CharField(choices=[('', 'Click to Select'), ('Cash', 'Cash'), ('Insurance', 'Insurance'), ('Corporate', 'Corporate')], default='CHOICES[0][0]', max_length=50),
        ),
    ]
