# Generated by Django 3.2 on 2022-02-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMHOnlinePatRfrApp', '0006_referral_details_patient_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral_details',
            name='payer_details',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
