# Generated by Django 3.2 on 2022-03-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMHOnlinePatRfrApp', '0008_auto_20220228_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral_details',
            name='empid',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='referral_details',
            name='posted_by',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
