# Generated by Django 3.2 on 2022-03-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMHOnlinePatRfrApp', '0009_auto_20220307_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role_master',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='role_master',
            name='role',
            field=models.SmallIntegerField(choices=[('ACCOUNTS', '1'), ('MARKETING HEAD', '2'), ('MARKETING EXECUTIVES', '3')], default=0),
        ),
    ]
