# Generated by Django 3.2 on 2022-03-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMHOnlinePatRfrApp', '0010_auto_20220307_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role_master',
            name='role',
            field=models.CharField(choices=[('1', 'ACCOUNTS'), ('2', 'MARKETING HEAD'), ('3', 'MARKETING EXECUTIVE')], default=0, max_length=10),
        ),
    ]
