# Generated by Django 3.2 on 2022-03-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMHOnlinePatRfrApp', '0011_alter_role_master_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral_details',
            name='speciality',
            field=models.CharField(default=' ', max_length=100, verbose_name='Speciality'),
        ),
        migrations.AlterField(
            model_name='referral_details',
            name='doc_ph',
            field=models.CharField(default='', max_length=10, verbose_name='Referred by Phone'),
        ),
        migrations.AlterField(
            model_name='referral_details',
            name='patient_ph',
            field=models.CharField(blank=True, max_length=10, verbose_name='Patient Phone'),
        ),
    ]
